<a href="https://colab.research.google.com/github/irissun9602/DeepLearningProject/blob/master/fully_connected_layer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Chap 1-2. 완전 연결 계층 구현

In [ ]:
import numpy as np

class FullyConnectedLayer(object):

  def __init__(self, num_inputs, layer_size, activation_fn):
    super().__init__()

    self.W = np.random.standard_normal((num_inputs, layer_size))
    self.b = np.random.standard_normal(layer_size)
    self.size = layer_size
    self.activation_fn = activation_fn


  def forward(self, x):
    z = np.dot(x, self.W) + self.b

    return self.activation_fn(z)



In [ ]:
np.random.seed(42)

# -1~1 사이 실수 2개 랜덤으로 고르기
x1 = np.random.uniform(-1, 1, 2).reshape(1, 2)
x2 = np.random.uniform(-1, 1, 2).reshape(1, 2)

# relu 활성화 함수 정의
relu_fn = lambda y: np.maximum(y,0)

layer = FullyConnectedLayer(2, 3, relu_fn)

out1 = layer.forward(x1)
print(out1)


[[0.28712364 0.         0.33478571]]


In [ ]:
out2 = layer.forward(x2)
print(out2)

[[0.         0.         1.08175419]]


In [ ]:
print(layer.W)

[[-0.23415337 -0.23413696  1.57921282]
 [ 0.76743473 -0.46947439  0.54256004]]
